//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionDesParc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGPEntities4 : DbContext
    {
        public DBGPEntities4()
            : base("name=DBGPEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_BILL> TB_BILL { get; set; }
        public virtual DbSet<TB_CLIENT> TB_CLIENT { get; set; }
        public virtual DbSet<TB_PAYMENT> TB_PAYMENT { get; set; }
        public virtual DbSet<TB_SELL> TB_SELL { get; set; }
        public virtual DbSet<TB_STOCK> TB_STOCK { get; set; }
        public virtual DbSet<TB_SUPPLIER> TB_SUPPLIER { get; set; }
        public virtual DbSet<TB_SUPPLIER_PAYMENTS> TB_SUPPLIER_PAYMENTS { get; set; }
        public virtual DbSet<TB_ARTICLE> TB_ARTICLE { get; set; }
        public virtual DbSet<TB_PURCHASE> TB_PURCHASE { get; set; }
    }
}
