//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionDesParc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ARTICLE
    {
        public int ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> ID_Purchase { get; set; }
        public string SupplierName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Unity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<double> SellingPrice2 { get; set; }
        public Nullable<double> Transport { get; set; }
        public Nullable<double> Unload { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> LoadingPrice { get; set; }
    
        public virtual TB_PURCHASE TB_PURCHASE { get; set; }
    }
}
