//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionDesParc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PURCHASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PURCHASE()
        {
            this.TB_ARTICLE = new HashSet<TB_ARTICLE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string SupplierName { get; set; }
        public string PaymentState { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ARTICLE> TB_ARTICLE { get; set; }
    }
}
