//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionDesParc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STOCK
    {
        public int ID { get; set; }
        public string ArticleName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> BarreInQuintale { get; set; }
        public string Type { get; set; }
        public string Unity { get; set; }
        public string Unity2 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Price2 { get; set; }
        public Nullable<double> loadingPrice { get; set; }
    }
}
